# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-07 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='message',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='polymorphic_ctype',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='users',
        ),
        migrations.RemoveField(
            model_name='eventchatroom',
            name='chatroom_ptr',
        ),
        migrations.RemoveField(
            model_name='eventchatroom',
            name='event',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.DeleteModel(
            name='Chatroom',
        ),
        migrations.DeleteModel(
            name='EventChatroom',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
