# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-28 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0002_auto_20170727_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.CharField(default='Dope event coming at you', max_length=5000),
            preserve_default=False,
        ),
    ]
