# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-09 22:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0002_auto_20170907_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_posts', to='play.User'),
            preserve_default=False,
        ),
    ]
