# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-14 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0003_event_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(max_length=1000),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
