# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-29 00:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0005_auto_20170821_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='name',
            new_name='title',
        ),
    ]
